version: "3.5"
services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: wallet_nginx
        environment:
            - DOCROOT
        volumes:
            - ./:/var/www/wallet
        ports:
            - "127.0.0.1:80:80"
        depends_on:
            - php
        links:
            - php
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: wallet_php
        environment:
            - DOCROOT=public
        volumes:
            - ./:/var/www/wallet
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - mysql
    mysql:
        platform: linux/amd64
        image: mysql:5.7
        container_name: wallet_mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=wallet
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./docker/mysql/volume:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wallet_pma
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            PMA_ARBITRARY: 1
        links:
            - mysql
    mailhog:
        image: mailhog/mailhog:latest
        container_name: wallet_mailhog
        ports:
            - "8003:1025"
            - "8100:8025"
